### ISSUE TITLE
Monitor Request Body not cleared when switching to request which does not have Body

### ISSUE THREAD

**Issue by nichwall** [pb33f/wiretap#99] opened 2024-02-17 17:12 UTC
When clicking around in the monitor to inspect requests, the `Body` option is correctly greyed out when switching to the `DELETE` request. However, if the previous view was the `Body` option of a request which had a Body, the bottom view does not reset/clear and instead shows the error `JSON.parse: unexpected character at line 1 column 1 of the JSON data` (what is shown in the screenshot).

Expected behavior is something to the effect of "Field does not exist for request" instead of showing a parse error. I'm not sure if the view should reset to the first valid option (like `Query`), since users will probably expect the same option to be selected when switching back to a request which does have a `Body`.

This occurs in wiretap 0.1.1.

![image](https://github.com/pb33f/wiretap/assets/5686638/d56bd741-af77-48d1-a1d6-61d44fe9b70b)

**Comment by daveshanley** [comment] 2024-05-12 17:30
This appears to be fixed in version `v0.1.12`. Cannot reproduce.

Video attached, as you can see the requests with no body are greyed out correctly, switching backward and forward between other requests renders out the different body types as expected.

https://github.com/pb33f/wiretap/assets/187345/aa883943-d031-4fb1-8a60-39206d73455c

**Closed by daveshanley** 2024-05-12 17:30 UTC
Labels: bug

**Comment by nichwall** [comment] 2024-05-12 18:05
Confirmed working for me in `v0.1.12` as well
